config/routes.rb
Rails.application.routes.draw do

  resources :posts
  resources :topics
  resources :users
  resources :sessions

  get '/login' => 'sessions#new', as: 'login'
  get '/logout' => 'sessions#destroy', as: 'logout'
  get '/sign_up' => 'users#new', as: 'sign_up'

  root 'topics#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :topic
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :user
  has_many :posts, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates_presence_of :password
  validates :email, presence: true, uniqueness: true

  has_many :topics
end

app/controllers/application_controller.rb
# require_relative '../policies/all'

class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  def current_user
    @current_user ||= session[:user_id].try{|id| User.find(id)}
  end

  include Authorizable
end

app/controllers/concerns/authorizable.rb
module Authorizable
  extend ActiveSupport::Concern

  included{ helper_method :allow }
  def allow(record, query)
    policy(record).send(query)
  end
  def authorize(record, query=params[:action])
    redirect_to root_url, notice:'Not authorize' unless allow(record, query)
  end
  def authorize_action(query=params[:action], record=nil)
    authorize(record, query)
  end

  private
  def policy_class(model=nil)
    model ||= params[:controller].singularize
    (model.to_s.camelize + 'Policy').constantize
  end

  def policy(record)
    @policies ||= {}
    @policies[record] ||= policy_class(record.try(:class)).new(current_user,record)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:topic_id, :content, :inline_images)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by_email(params[:email])
    if user.try(:authenticate, params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice:'Logged in.'
    else
      flash.now[:error] = 'Invalid password or username'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice:'Logged out.'
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic_and_authorize, only: [:show, :edit, :update, :destroy]
  before_action :authorize_action, only: [:index, :new]

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all.includes(:user, :posts)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @topics }
    end
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @topic }
    end
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = current_user.topics.build(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render json: @topic, status: :created }
      else
        format.html { render action: 'new' }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end
  def set_topic_and_authorize
    set_topic

  end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:name, :sticky)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :admin)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}
    %title my_385

    / HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
    /[if lt IE 9]
      = javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js"

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-inverse.navbar-fixed-top{:role => "navigation"}
      .container
        .navbar-header
          %button.navbar-toggle.collapsed{:type => "button", :data => {:toggle => "collapse", :target => "#navbar"}, :aria => {:expanded => "false", :controls => "navbar"} }
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to "Project name", "#", :class => "navbar-brand"
        #navbar.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li.active
              %a{:href => "/"} Home
            %li
              %a{:href => "#about"} About
            %li
              %a{:href => "#contact"} Contact
          %ul.nav.navbar-nav.navbar-right
            - if current_user
              %li=link_to "Profile #{current_user.email}", current_user
              %li=link_to "Log Out", logout_path
            - else
              %li=link_to 'Sign Up', sign_up_path
              %li=link_to 'Log In', login_path
    .container
      - flash.each do |name, msg|
        = content_tag :div, :class => "alert alert-#{%w[alert error].include?(name.to_s) ? "danger" : "success" } alert-dismissable", :role => "alert" do
          %button.close{:type => "button", :data => {:dismiss => "alert"} }
            %span{:aria => {:hidden => "true"} } &times;
            %span.sr-only Close
          = msg
      = yield

app/views/posts/_form.html.haml
= simple_form_for(@post) do |f|
  = f.error_notification

  .form-inputs
    = f.association :topic
    = f.input :content
    = f.input :inline_images

  .form-actions
    = f.button :submit

app/views/posts/_post.html.haml
- if allow(post, :show)
  %p
    = link_to_if allow(post, :show), 'Show', post
    = link_to_if allow(post, :edit), 'Edit', edit_post_path(post)
    = link_to_if allow(post, :destroy), 'Destroy', post, :data => { confirm: 'Are you sure?' }, :method => :delete
  %p= post.content

app/views/posts/edit.html.haml
.page-header
  = link_to posts_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to @post, :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Show
  %h1 Editing post

= render 'form'

app/views/posts/index.html.haml
.page-header
  = link_to new_post_path, :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-plus
    New Post
  %h1 Listing posts

.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th Topic
        %th Content
        %th Inline images
        %th
        %th
        %th

    %tbody
      - @posts.each do |post|
        %tr
          %td= post.topic
          %td= post.content
          %td= post.inline_images
          %td= link_to 'Show', post
          %td= link_to 'Edit', edit_post_path(post)
          %td= link_to 'Destroy', post, :data => { confirm: 'Are you sure?' }, :method => :delete

app/views/posts/new.html.haml
.page-header
  = link_to posts_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h1 New post

= render 'form'

app/views/posts/show.html.haml
.page-header
  = link_to posts_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to edit_post_path(@post), :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-pencil
    Edit
  %h1 Show post


%dl.dl-horizontal
  %dt Topic:
  %dd= @post.topic
  %dt Content:
  %dd= @post.content
  %dt Inline images:
  %dd= @post.inline_images

app/views/topics/_form.html.haml
= simple_form_for(@topic) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :sticky
    = f.association :user

  .form-actions
    = f.button :submit

app/views/topics/edit.html.haml
.page-header
  = link_to topics_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to @topic, :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Show
  %h1 Editing topic

= render 'form'

app/views/topics/index.html.haml
.page-header
  - if allow(Topic.new, :new)
    = link_to new_topic_path, :class => 'btn btn-primary' do
      %span.glyphicon.glyphicon-plus
      New Topic
  %h1 Listing topics

.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th Name
        %th Sticky
        %th User
        %th
        %th
        %th

    %tbody
      - @topics.each do |topic|
        - if allow(topic, :show)
          %tr
            %td=link_to topic.name, topic
            %td= topic.sticky
            %td= topic.user.try(:email)
            %td= link_to 'Show', topic
            %td= link_to_if allow(topic, :edit), 'Edit', edit_topic_path(topic)
            %td= link_to_if allow(topic, :destroy), 'Destroy', topic, :data => { confirm: 'Are you sure?' }, :method => :delete

app/views/topics/new.html.haml
.page-header
  = link_to topics_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h1 New topic

= render 'form'

app/views/topics/show.html.haml
.page-header
  = link_to topics_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  - if allow(@topic, :edit)
    = link_to edit_topic_path(@topic), :class => 'btn btn-primary' do
      %span.glyphicon.glyphicon-pencil
      Edit
  - if allow(Post.new, :new)
    = link_to new_topic_path, :class => 'btn btn-primary' do
      %span.glyphicon.glyphicon-plus
      New Post
  %h1= @topic.name
  %p by #{@topic.user.try(:email)}

= render @topic.posts

app/views/users/_form.html.haml
= simple_form_for(@user) do |f|
  = f.error_notification

  .form-inputs
    = f.input :email
    = f.input :password
    = f.input :password_confirmation
    = f.input :admin

  .form-actions
    = f.button :submit

app/views/users/edit.html.haml
.page-header
  = link_to users_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to @user, :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Show
  %h1 Editing user

= render 'form'

app/views/users/index.html.haml
.page-header
  = link_to new_user_path, :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-plus
    New User
  %h1 Listing users

.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th Email
        %th Password digest
        %th Admin
        %th
        %th
        %th

    %tbody
      - @users.each do |user|
        %tr
          %td= user.email
          %td= user.password_digest
          %td= user.admin
          %td= link_to 'Show', user
          %td= link_to 'Edit', edit_user_path(user)
          %td= link_to 'Destroy', user, :data => { confirm: 'Are you sure?' }, :method => :delete

app/views/users/new.html.haml
.page-header
  = link_to users_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h1 New user

= render 'form'

app/views/users/show.html.haml
.page-header
  = link_to users_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to edit_user_path(@user), :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-pencil
    Edit
  %h1 Show user

%dl.dl-horizontal
  %dt Email:
  %dd= @user.email
  %dt Password digest:
  %dd= @user.password_digest
  %dt Admin:
  %dd= @user.admin